from enum import StrEnum


class OrderStatus(StrEnum):
    CREATED = "CREATED"
    AWAITING_CANDIDATES = "AWAITING_CANDIDATES"
    AWAITING_SELECTION = "AWAITING_SELECTION"
    PROVIDER_SELECTED = "PROVIDER_SELECTED"
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class ApplicationStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class ReviewDirection(StrEnum):
    CLIENT_TO_PROVIDER = "CLIENT_TO_PROVIDER"
    PROVIDER_TO_CLIENT = "PROVIDER_TO_CLIENT"
