"""create service_order_history table

Revision ID: 49bc4169a8b4
Revises: eff1b033855f
Create Date: 2026-05-21 12:14:09.514936

"""

# revision identifiers, used by Alembic.
revision = "49bc4169a8b4"
down_revision = "eff1b033855f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
