"""add provider_finished_at to service_orders

Revision ID: 609724dd16c5
Revises: a070f30272fb
Create Date: 2026-05-21 11:31:56.475073

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "609724dd16c5"
down_revision = "a070f30272fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "idempotency_keys", ["id"])
    op.create_unique_constraint(None, "payment_transactions", ["id"])
    op.create_unique_constraint(None, "payments", ["id"])
    op.add_column(
        "service_orders",
        sa.Column("provider_finished_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_orders", "provider_finished_at")
    op.drop_constraint(None, "payments", type_="unique")
    op.drop_constraint(None, "payment_transactions", type_="unique")
    op.drop_constraint(None, "idempotency_keys", type_="unique")
    # ### end Alembic commands ###
