"""create reviews table

Revision ID: eff1b033855f
Revises: 609724dd16c5
Create Date: 2026-05-21 11:50:11.140267

"""



# revision identifiers, used by Alembic.
revision = "eff1b033855f"
down_revision = "609724dd16c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
